name: 15-minute-cron
on:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: curl --request GET --url ${{secrets.DEPLOY_URL}}
